### ISSUE TITLE
入场用户ID始终为111111, 并且nickName字段会被隐藏,是因为匿名访问吗

### ISSUE THREAD

**Issue by yaoyaochil** [jwwsjlm/douyinLive#11]
`{
    "common": {
        "method": "WebcastMemberMessage",
        "msgId": "7445201728116397619",
        "roomId": "7445184962799651595",
        "isShowMsg": true,
        "displayText": {
            "key": "invalid_key_placeholder",
            "defaultPattern": "{0:user} 来了",
            "defaultFormat": {
                "color": "#b8ffffff",
                "weight": 400
            },
            "pieces": [
                {
                    "type": 11,
                    "format": {
                        "color": "#8CE7FF",
                        "weight": 400
                    },
                    "uservalue": {
                        "user": {
                            "id": "111111",
                            "nickName": "玲***",
                            "AvatarThumb": {
                                "url": "https://p11-webcast.douyinpic.com/img/webcast/small_DefAvatar.png~tplv-obj.image",
                                "altText": "webcast/small_DefAvatar.png"
                            },
                            "BadgeImageList": [
                                {
                                    "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                                    "width": "16",
                                    "height": "32"
                                }
                            ],
                            "FollowInfo": {
                                "followingCount": "1162",
                                "followerCount": "77",
                                "followerCountStr": "77",
                                "followingCountStr": "1162"
                            },
                            "PayGrade": {
                                "level": "7",
                                "newImIconWithLevel": {
                                    "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                                    "width": "16",
                                    "height": "32"
                                },
                                "newLiveIcon": {
                                    "url": "https://p3-webcast.douyinpic.com/img/webcast/aweme_pay_grade_2x_5_9.png~tplv-obj.image",
                                    "width": "12",
                                    "height": "12"
                                }
                            },
                            "FansClub": {
                                "data": {
                                    "badge": {
                                        "icons": {
                                            "0": {}
                                        }
                                    }
                                }
                            },
                            "idStr": "111111"
                        }
                    }
                }
            ]
        },
        "foldType": "1",
        "anchorFoldType": "1",
        "priorityScore": "42000",
        "anchorFoldTypeV2": "3",
        "appId": "1128"
    },
    "user": {
        "id": "111111",
        "nickName": "玲***",
        "AvatarThumb": {
            "url": "https://p11-webcast.douyinpic.com/img/webcast/small_DefAvatar.png~tplv-obj.image",
            "altText": "webcast/small_DefAvatar.png"
        },
        "BadgeImageList": [
            {
                "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                "width": "16",
                "height": "32"
            }
        ],
        "FollowInfo": {
            "followingCount": "1162",
            "followerCount": "77",
            "followerCountStr": "77",
            "followingCountStr": "1162"
        },
        "PayGrade": {
            "level": "7",
            "newImIconWithLevel": {
                "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                "width": "16",
                "height": "32"
            },
            "newLiveIcon": {
                "url": "https://p3-webcast.douyinpic.com/img/webcast/aweme_pay_grade_2x_5_9.png~tplv-obj.image",
                "width": "12",
                "height": "12"
            }
        },
        "FansClub": {
            "data": {
                "badge": {
                    "icons": {
                        "0": {}
                    }
                }
            }
        },
        "idStr": "111111"
    },
    "memberCount": "1124",
    "action": "1",
    "anchorDisplayText": {
        "key": "invalid_key_placeholder",
        "defaultPattern": "{0:user} 来了",
        "defaultFormat": {
            "color": "#b8ffffff",
            "weight": 400
        },
        "pieces": [
            {
                "type": 11,
                "format": {
                    "color": "#8CE7FF",
                    "weight": 400
                },
                "uservalue": {
                    "user": {
                        "id": "111111",
                        "nickName": "玲***",
                        "AvatarThumb": {
                            "url": "https://p3-webcast.douyinpic.com/img/webcast/small_DefAvatar.png~tplv-obj.image",
                            "altText": "webcast/small_DefAvatar.png"
                        },
                        "BadgeImageList": [
                            {
                                "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                                "width": "16",
                                "height": "32"
                            }
                        ],
                        "FollowInfo": {
                            "followingCount": "1162",
                            "followerCount": "77",
                            "followerCountStr": "77",
                            "followingCountStr": "1162"
                        },
                        "PayGrade": {
                            "level": "7",
                            "newImIconWithLevel": {
                                "url": "https://p3-webcast.douyinpic.com/img/webcast/new_user_grade_level_v1_7.png~tplv-obj.image",
                                "width": "16",
                                "height": "32"
                            },
                            "newLiveIcon": {
                                "url": "https://p3-webcast.douyinpic.com/img/webcast/aweme_pay_grade_2x_5_9.png~tplv-obj.image",
                                "width": "12",
                                "height": "12"
                            }
                        },
                        "FansClub": {
                            "data": {
                                "badge": {
                                    "icons": {
                                        "0": {}
                                    }
                                }
                            }
                        },
                        "idStr": "111111"
                    }
                }
            }
        ]
    },
    "publicAreaCommon": {
        "imAction": 2
    },
    "buriedPoint": {
        "enter_tip_type": "0"
    }
}`

**Comment by yaoyaochil** [comment]
多次测试，发现这个现象是偶发事件

**Comment by jwwsjlm** [comment]
不太清楚 对于具体内容没有研究过 应该是匿名直播间原因吧

**Comment by tianxia1** [comment]
这是因为主播开启了一个设置，不能看直播间观众的信息，一般电公电母多
