### ISSUE TITLE
部分直播间无法连接

### ISSUE THREAD

**Issue by zhangyuxin123** [jwwsjlm/douyinLive#2]
您好！
我在使用您的项目时，发现有些直播间在浏览器中是无法观看直播的，这些直播间就无法连接弹幕（连接不成功），请问这个您有好的解决方案吗？

**Comment by jwwsjlm** [comment]
什么直播间 有没有地址..没事了我蹲一下看看

**Comment by zhangyuxin123** [comment]
t872329507，方便的话您加一下联系方式（地球号）等他直播了   我告诉您
