### ISSUE TITLE
err:websocket: bad handshake

### ISSUE THREAD

**Issue by cnjingrui** [jwwsjlm/douyinLive#3]
PS D:\Users\Desktop\dydm> .\douyinlive.exe --room 96294557169 --port 18080
2024/06/23 23:25:21 false
2024/06/23 23:25:21 wss服务启动成功,链接地址为:ws://127.0.0.1:18080/ws
直播地址:96294557169
2024/06/23 23:25:23 链接失败: err:websocket: bad handshake
roomid:7383669129611430656
 ttwid:1%7CtWSFGo0dOE-QGlZRNK1bs2oxZY3tJELFdEcrUswUC7E%7C1719156321%7Cb1d0c05168b0d12e087b8e36803078b2574f8d6d32a2355309d4bd8d8fc51e06

**Comment by jwwsjlm** [comment]
推荐这个https://gitee.com/haodong108/dy-barrage-grab 一劳永逸.拦截进程pc抖音客户端.
抖音网页版现在更新了需要signature参数 jsvmp的 有点麻烦

**Comment by athlon18** [comment]
func (w *Webmssdk) sign() (err error) {
	vm := goja.New()
	_, err = vm.RunString(`document={};window={};navigator={"userAgent":"` + w.ua + `"};` + w.js)
	if err != nil {
		return
	}
	// 加载函数
	sign, ok := goja.AssertFunction(vm.Get("get_sign"))
	if !ok {
		panic("Not a function")
	}

	result, err := sign(goja.Undefined(), vm.ToValue(w.params()))
	if err != nil {
		return
	}
	//fmt.Printf("result:%v\n", result)
	w.Sign = result.String()
	return
}

**Comment by jwwsjlm** [comment]
> func (w *Webmssdk) sign() (err error) { vm := goja.New() _, err = vm.RunString(`document={};window={};navigator={"userAgent":"` + w.ua + `"};` + w.js) if err != nil { return } // 加载函数 sign, ok := goja.AssertFunction(vm.Get("get_sign")) if !ok { panic("Not a function") }
> 
> ```
> result, err := sign(goja.Undefined(), vm.ToValue(w.params()))
> if err != nil {
> 	return
> }
> //fmt.Printf("result:%v\n", result)
> w.Sign = result.String()
> return
> ```
> 
> }
嗯看了一下 检测的倒是只有ua 补个ua上去能出参.但是生成的signature好像还是用不了还再排查
![微信截图_20240624015835](https://github.com/jwwsjlm/douyinLive/assets/48446617/f68f14da-30d8-40fc-b0fc-6af3021003e5)

**Comment by athlon18** [comment]
![image](https://github.com/jwwsjlm/douyinLive/assets/44226614/88aa41ec-901e-4de6-879b-a4b1d7810926)

**Comment by jwwsjlm** [comment]
> ![image](https://private-user-images.githubusercontent.com/44226614/342106224-88aa41ec-901e-4de6-879b-a4b1d7810926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjYxNDAsIm5iZiI6MTcxOTE2NTg0MCwicGF0aCI6Ii80NDIyNjYxNC8zNDIxMDYyMjQtODhhYTQxZWMtOTAxZS00ZGU2LTg3OWItYTRiMWQ3ODEwOTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NmJlY2Y4OTgzNmNmNmU1MTEyMjI2YzE2YmUzNDQ4NmIyZjg5NGNiOWE3ZDY1ODRhZGE1ZGYyMWEyMDBjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v2Tg1ySymolnSyBq1z-dlDR0lm4xXRjwdQXNGYkiZAY) ![image](https://private-user-images.githubusercontent.com/44226614/342106293-07050811-6e23-447c-a8bf-53010181e34b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjYxNDAsIm5iZiI6MTcxOTE2NTg0MCwicGF0aCI6Ii80NDIyNjYxNC8zNDIxMDYyOTMtMDcwNTA4MTEtNmUyMy00NDdjLWE4YmYtNTMwMTAxODFlMzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YWZmMzdjODg5ZmVhNWQ5YjRmNDk3MWNmYTZlZjFhNWEzNjU5ZjQyN2NkNjQ2ZTk2NzFjZmNkZmQzZjM0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WagEAo0A_9D_DX0cszWK6b3pYTMhaxgMDFaLRE7fmDY)

![微信截图_20240624020531](https://github.com/jwwsjlm/douyinLive/assets/48446617/049be97f-7953-403e-937d-2510a8f58080)
嗯生成部分都匹配测试了.跟网页计算的md5 hex倒是没什么出入.但是生成的就是不可用 还再研究

**Comment by jwwsjlm** [comment]
> + `"};`

...好吧 我本来也在逆这个 拿到了jsvmp这段代码.我补了个ua和window这种常用的 能正常出参...但是一直不行.然后我是看到这个https://github.com/LyzenX/DouyinLiveRecorder/blob/main/dylr/util/webmssdk.js py的了..我看js代码大差不错..都是把他原有的扣出来 然后py的也是补了个dom头..我想着应该没问题的..我没用他这个..刚刚我给他这个js代码复制过来直接运行的话正常了..
https://github.com/hua0512/stream-rec/blob/f5a13e5ccc7df051b4f537321ffa259275aaa1ba/platforms/src/main/resources/douyin-webmssdk.js

**Comment by cnjingrui** [comment]
@jwwsjlm 感谢大佬幸苦付出，现在一切正常
