### ISSUE TITLE
每隔一段时间，程序会崩溃

### ISSUE THREAD

**Issue by fanchenhao** [jwwsjlm/douyinLive#4]
隔30-60分钟程序会崩溃

**Comment by jwwsjlm** [comment]
有无崩溃日志。

**Comment by fanchenhao** [comment]
> 有无崩溃日志。

每次退出的时候，都是冷不丁，就没了，啥也监听不到了，需要重新打开才可以

**Comment by jwwsjlm** [comment]
https://github.com/jwwsjlm/douyinLive/releases/tag/v1.0.5
试试断线重连.你要先打开cmd 然后
douyinlive.exe --room <目标房间号>
cmd窗口应该不会直接崩溃消失呀

**Comment by jwwsjlm** [comment]
https://github.com/jwwsjlm/douyinLive/releases/tag/v1.0.5
试试这个版本呢

**Comment by jwwsjlm** [comment]
https://github.com/jwwsjlm/douyinLive/releases/tag/v1.0.5
试试这个 改了一下gzip部分.怀疑是因为gzip每次都是创建一个新的.导致内存崩溃?
