### ISSUE TITLE
20多秒一次重连正常吗？

### ISSUE THREAD

**Issue by gzw13999** [jwwsjlm/douyinLive#6]
2024/07/31 02:14:52 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:14:52 尝试重新连接...
2024/07/31 02:14:53 重连成功
2024/07/31 02:15:14 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:15:14 尝试重新连接...
2024/07/31 02:15:14 重连成功
2024/07/31 02:15:35 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:15:35 尝试重新连接...
2024/07/31 02:15:36 重连成功
2024/07/31 02:15:57 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:15:57 尝试重新连接...
2024/07/31 02:15:57 重连成功
2024/07/31 02:16:18 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:16:18 尝试重新连接...
2024/07/31 02:16:18 重连成功
2024/07/31 02:16:40 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:16:40 尝试重新连接...
2024/07/31 02:16:40 重连成功
2024/07/31 02:17:01 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:17:01 尝试重新连接...
2024/07/31 02:17:01 重连成功
2024/07/31 02:17:22 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:17:22 尝试重新连接...
2024/07/31 02:17:23 重连成功
2024/07/31 02:17:44 读取消息失败- websocket: close 1006 (abnormal closure): unexpected EOF [] -1
2024/07/31 02:17:44 尝试重新连接...
2024/07/31 02:17:44 重连成功

**Comment by jwwsjlm** [comment]
直播间发一下

**Comment by gzw13999** [comment]
昨晚随便进了个直播间测试是这样的，今天我观察下又好了。也有可能昨天用无头模式多次调试IP被风控了。

**Comment by jwwsjlm** [comment]
嗯 不过本项目只是为了学习下protobuf的解析和ws的链接.实际应用并无太多参考意义.
